<a href="https://colab.research.google.com/github/satoyos/Neural_Networks_from_scratch/blob/master/Perceptron_AND_operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Perceptron AND operator

![alt text](https://drive.google.com/uc?id=1EVKYuVhLOMcvCOo4x2WDe9-rzbsIqe47)



## Inputs, outputs and weights

In [ ]:
import numpy as np

In [ ]:
inputs = np.array([[0,0], [0,1], [1,0], [1,1]])

In [ ]:
inputs.shape

(4, 2)

In [ ]:
outputs = np.array([0, 0, 0, 1])

In [ ]:
outputs.shape

(4,)

In [ ]:
weights = np.array([0.0, 0.0])

In [ ]:
learning_rate = 0.1

## Step function

In [ ]:
def step_function(sum):
  if (sum >= 1):
    return 1
  return 0

## Calculate output

In [ ]:
def calculate_output(instance):
  s = instance.dot(weights)
  return step_function(s)

In [ ]:
calculate_output(np.array([[1,1]]))

0

## Train

In [ ]:
len(outputs)

4

In [ ]:
inputs[3]

array([1, 1])

In [ ]:
0 - 1

-1

In [ ]:
abs(0 - 1)

1

In [ ]:
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [ ]:
inputs[1]

array([0, 1])

In [ ]:
inputs[1][0]

0

In [ ]:
inputs[1][1]

1

In [ ]:
def train():
  total_error = 1
  while (total_error != 0):
    total_error = 0
    for i in range(len(outputs)):
      prediction = calculate_output(inputs[i])
      error = abs(outputs[i] - prediction)
      total_error += error
      if error > 0:
        for j in range(len(weights)):
          weights[j] = weights[j] + (learning_rate * inputs[i][j] * error)
          print('Weight updated: ' + str(weights[j]))
    print('Total error: ' + str(total_error))

In [ ]:
train()

Weight updated: 0.1
Weight updated: 0.1
Total error: 1
Weight updated: 0.2
Weight updated: 0.2
Total error: 1
Weight updated: 0.30000000000000004
Weight updated: 0.30000000000000004
Total error: 1
Weight updated: 0.4
Weight updated: 0.4
Total error: 1
Weight updated: 0.5
Weight updated: 0.5
Total error: 1
Total error: 0


## Classification

In [ ]:
weights

array([0.5, 0.5])

In [ ]:
calculate_output(np.array([0,0]))

0

In [ ]:
calculate_output(np.array([0,1]))

0

In [ ]:
calculate_output(np.array([1,0]))

0

In [ ]:
calculate_output(np.array([1,1]))

1